### ISSUE TITLE
DevTools script tag must be in body tag

### ISSUE THREAD

**Issue by SQReder** [PuruVJ/vite-preset-react#2]
DevTools injection tag must be in `head` or `body` tag
currently id appended at the end of the index.html
![image](https://user-images.githubusercontent.com/1519753/116048606-0252c100-a67e-11eb-921d-9ea78bbffd4a.png)

see spec: https://www.w3schools.com/js/js_whereto.asp

suggested fix:
replace `code += '<script />'` with `code.replace('</body>', '<script /></body>')`

**Comment by PuruVJ** [comment]
Hi. Thanks for pointing it out.

This is a temporary thing. Sometimes, some index.html files don't have `body` tag, and browser will still accept it. So for now, I'm appending it to the bottom of the file. The ideal target would be to append it to the top of the index.js file. 

If you got a solution to this problem, I'll be happy to see it.

**Comment by SQReder** [comment]
I think, we could just fallback sequentially from closing tag of `head`, then `body` and if none of them found just append to the end of index.html

**Comment by PuruVJ** [comment]
Hmm, that seems doable. I'll implement that

**Comment by SQReder** [comment]
Take a look, pls

**Comment by PuruVJ** [comment]
Fixed in  v1.2.1
