### ISSUE TITLE
Identifier 'React' has already been declared

### ISSUE THREAD

**Issue by aladdin-add** [PuruVJ/vite-preset-react#5]
```bash
Uncaught SyntaxError: Identifier 'React' has already been declared
```

I'm new to the vite, but it seems the preset auto inject `import react from 'react'`. can this be optional?

**Comment by PuruVJ** [comment]
It could be optional, you're right. I built this preset as an opinionated plugin, but IG adding in this config option won't really break anything.

**Comment by PuruVJ** [comment]
Released a new version with `injectReact` function. Upgrade to `1.2.0` to use it. Do notify when this issue is resolved for you. Thank you for raising this issue.

**Comment by aladdin-add** [comment]
wow, thanks for the quick fix!
