### ISSUE TITLE
repo was not shown in npm page

### ISSUE THREAD

**Issue by aladdin-add** [PuruVJ/vite-preset-react#8]
![image](https://user-images.githubusercontent.com/13050025/141606450-267219f8-02d2-4ca1-8af9-6c0d54702d92.png)

looks like this line does not working as expected:
https://github.com/PuruVJ/vite-preset-react/blob/cf0db6a72cb47e97d86e0a1a34a14b65d62484c0/package.json#L20

**Comment by PuruVJ** [comment]
Thanks, fixed now
